# 通过本地编译的形式运行
# 可以随时修改源代码后 repackage 然后重新构建本地镜像
version: '3.3'
services:

  # admin 服务
  blog-admin:
    image: blog-admin:latest
    restart: always
    container_name: blog-admin
    env_file:
      - .env
    volumes:
      - ${ONEBLOG_APP_DIR}:/var/tmp/oneblog
    ports:
      - 8085:8085
    networks:
      - oneblog

  # admin 服务
  blog-web:
    image: blog-web:latest
    restart: always
    container_name: blog-web
    env_file:
      - .env
    volumes:
      - ${ONEBLOG_APP_DIR}:/var/tmp/oneblog

    ports:
      - 8443:8443
    networks:
      - oneblog

networks:
  oneblog:
    driver: bridge
